name: Deploy stories

on:
  push:
    branches: [master]

jobs:
  deploy_stories:
    name: Deploy stories
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn
      - name: Build stories
        run: yarn build:demo --base-href /k8s-form-in-action/demo/ --deploy-url /k8s-form-in-action/demo/
      - name: Deploy
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          build_dir: demo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
